### ISSUE TITLE
Error retreiving temperature

### ISSUE THREAD

**Issue by TerrorSource** [fabianblom/Toon-Android#30] opened 2019-04-09 06:06 UTC
App does not display current temperature
See screenshot.

Settings:
IP: ip of the toon
Port: 80

![ToonAndroid](https://user-images.githubusercontent.com/20524866/55776775-1ed32f00-5a9e-11e9-9e53-a827e01dfdc4.jpeg)

**Comment by Inversion-NL** [comment] 2019-04-09 08:25
Duplicate of #13

**Closed as completed by Inversion-NL** 2019-04-09 08:25 UTC
Labels: duplicate
